### ISSUE TITLE
Icon only sidebar?

### ISSUE THREAD

**Issue by AkariYui1** [Naezr/ShyFox#107]
As mentioned in #81, I know it's hard to do, but I have a small idea like this (Just a small idea, not a request).
Rather than completely hide the whole sidebar using UC, how about turning it into an icon-only sidebar (with tab's icon only and nothing else, can also be open on hover but up to you). And using the Clear view mode to completely hide it as usual?
An example of this: https://www.reddit.com/r/FirefoxCSS/comments/1e9084u/sidebery_plus

**Comment by Naezr** [comment]
It's an interesting idea, and even quite realizable. But there are some obstacles still at the time of thinking about it.

- First of all, macOS. On other systems, where the window control buttons are on the right side of the window, these buttons adapt to the circumstances and can be positioned both vertically and horizontally. When those buttons are on the left, there is no vertical state because the sidebar is wide enough to fit the buttons horizontally, even if the navbar is hidden. This goes in my favor because I almost don't have to touch those buttons on macOS to do this. If you add a thin sidebar, you'll have to do something about the window control buttons. I don't have an Apple device, so I can't implement it for macOS properly.

- Secondly, the sidebar. What to do with pinned tabs? I had the idea of stacking them on top of each other like a stack of cards, and sliding them apart when you hover over the sidebar. But the last time I tried to implement this, it didn't work. Alternatively, pinned tabs can be placed vertically with other tabs. But then tabs will have different vertical position in thin mode and when hovering over the sidebar. It is also unclear what to do with the bookmarks bar.

In general, there's a lot of things to solve before implementation, but I haven't come up with anything good yet

**Comment by AkariYui1** [comment]
Thank you for your response. Firstly, it's true that it's hard to implement this on macOS, I'll try to see if I can come up with any idea. Second of which, I love your card stacking idea, but how about just make the pinned tabs hover out in a different box
You can go with anything suitable for you, hope this help
A small concept I could think of (my Photoshop skills are -1/10) 
![Untitled-1](https://github.com/user-attachments/assets/7b2c4dda-4dbe-4fe0-9aa4-548ad777c15a)

**Comment by Naezr** [comment]
> Firstly, it's true that it's hard to implement this on macOS

The problem isn't the difficulty of implementing for macOS, it's that I don't have access to macOS and therefore can't do anything.

> make the pinned tabs hover out in a different box

A sidebar is essentially a small browser window in which a web page (Sidebery in this case) is open. One solid element cannot be divided into two pieces with different styles for them

**Comment by Naezr** [comment]
This will be possible with the new sidebar from Firefox Nightly. When I finish ShyFox 4.0 and Firefox developers finish the new sidebar, this will be a reality
