### ISSUE TITLE
How do i customise the homepage?

### ISSUE THREAD

**Issue by duckworx** [Naezr/ShyFox#113]
![image](https://github.com/user-attachments/assets/da9f8ac9-b61d-4cac-bfb1-f6cec62169c1)

**Comment by Naezr** [comment]
In main files background color under name of the pinned link does not change. I sent a small [fix to nightly](https://github.com/Naezr/ShyFox/commit/8e766ffb3971939311bca50900775c0dcf66213e) branch, use [files from there](https://github.com/Naezr/ShyFox/archive/refs/heads/nightly.zip)

[Запись экрана от 2024-07-24 22-40-48.webm](https://github.com/user-attachments/assets/2735d712-b782-43b1-8ab2-1dbc5c6f4ba6)

-------

It looks like your theme has colored the text on the new tab. Didn't know about it working that way. I'll experiment with using the theme colors for the new tab. Right now they're hardcoded

**Comment by Naezr** [comment]
I learned that color themes can set the background color of a new tab. There is a separate variable for this. However, it doesn't work in ShyFox because I didn't know about it and set the colors manually... I'll fix it in next update, thanks for hint

![image](https://github.com/user-attachments/assets/c808a051-0e0b-402c-a997-ca53a3f61f2e)

**Comment by Naezr** [comment]
Since 3.7.3 new tab respects `New Tab Background Color` variable from theme
