### ISSUE TITLE
Make the sideberry background grabbable?

### ISSUE THREAD

**Issue by owosoup** [Naezr/ShyFox#133]
The borders of this theme allow me to move the window, in all parts of the window, up, down, left and right. I assume it's because it's the background?

It's also maybe enabled by Klassy which allows window dragging from empty spaces. If it's not intended, it's still very nice!

My question is : can the sideberry background be used for this, can CSS allow it? It would be super cool and ergonomic to drag around the sideberry background instead of having to pinpoint a small border.
This is especially good for people who disable window buttons for various reasons, they have less space to work with!

If you can't, it's ok. If you can, take the time you need. <3 This theme is the best!

![image](https://github.com/user-attachments/assets/7b98b780-b15c-4818-a55e-fb6ce5e0fc3f)

**Comment by Naezr** [comment]
Sidebar content is essentially a separate web page, and is categorized as Content, just like a website opened in the main window.

The property that allows you to drag the window is only available in the Chrome category - toolbars, buttons, browser interface in general. I've prescribed drag areas for each edge separately, it doesn't work that way by default.

I plan to add an option to use native tabs instead of Sidebery, there you can add dragging for empty spaces. Native tabs are a part of Chrome.

If anything, Chrome refers to the browser interface. The shell that surrounds the content. Google named their browser after it.

**Comment by owosoup** [comment]
Can't wait for 4.0 then! But it won't look the same... I think I'll stay with sideberry ~
Thanks for the quick answer! I get it now. Maybe a sideberry update will come and make this possible?

**Comment by Naezr** [comment]
> But it won't look the same... I think I'll stay with sideberry ~

Yeah, Sidebery is really cool. Native vertical tabs will be just an option and will be much less functional.

> Maybe a sideberry update will come and make this possible?

Technically impossible. I'll say it again: 

Sidebery from the browser's point of view is just a locally opened web page. Web pages have standard tools available to them, unified for all browsers. 

Firefox's interface is a level above. Although it is built on the same web technologies, Firefox provides additional functionality to make it easier to build your own interface. For example, you can read settings from `about:config`, give an element a window drag property, and much more.

Such privileges are not available to ordinary web pages. And everything that is open in the sidebar is a regular web page. 

In fact, extension pages have a little more power than regular web pages. For example, reading theme colors. But the level of privileges for extensions is still lower than for the interface.
