### ISSUE TITLE
The extension doesn't use the setting from the last active window until click tabs in sideberry

### ISSUE THREAD

**Issue by quocjq** [Naezr/ShyFox#147]
### Issue
I think this is a Firefox problem when opening a new window FF will not automatically run the extension.
https://github.com/user-attachments/assets/7ba9b82c-9e6e-4864-9ca7-c9f7f9cfa788
### Steps to reproduce
Restart the Firefox browser
### Something that I suggested
1/ Can you add feature that toggle to turn off url bar or move the url bar to the search bar in sideberry?
I find it disgusting when opening popup search bar and floating bar at same time:
https://github.com/user-attachments/assets/385c7ac3-4cce-4ae3-906d-9e2c3475e957
2/Feature that when your mouse hover left of right of window, it will open sticked sidebar? It had to explan but it is something like this:
https://github.com/user-attachments/assets/53076204-5bed-47ef-aa6b-0509c8a25ceb
3/Feature that toggle to change url bar from top to bottom and reverse, it's painful when I need to use url bar to bookmark or change site information. Actually if it have (1), I dont need it anymore.

Btw, your Shyfox is so charming that I don't need wife anymore.

**Comment by Naezr** [comment]
> I think this is a Firefox problem when opening a new window FF will not automatically run the extension.

I think it's partly a Firefox problem and partly an extension problem. Firefox doesn't send a message that the window is focused when the window is created. And the extension's logic is entirely based on what window is currently focused. The extension needs to receive the information that a window with some ID is focused in order to apply a title prefix to it.

------------------------------------------------

Regarding the rest of the suggestions. I'm not quite sure what you want. However, you can check out the discussion tab and see the ShyFox 4.0 teaser. You might find what you need in the 4.0 functionality. It will be a constructor where you can build either ShyFox 3.0 or Arc Browser or something else. There is already an [Alpha version](https://github.com/Naezr/ShyFox/tree/4.0-alpha), but it is very far from being ready

**Comment by quocjq** [comment]
Regarding to suggestion 1, I think arc browser will be the best example:
https://static1.howtogeekimages.com/wordpress/wp-content/uploads/2023/04/arc_browser_featured.jpg?q=50&fit=crop&w=1100&h=618&dpr=1.5
This is an image that I found. And looking into it, you can see the url bar is located in sidebar, which loaykhalifa have already mentioned (I havent see it till now).
The teaser video already have my second desire but a little bit difference, I supposed that the nav, toolbar and sidebar is turn on or off when hover the mouse instead of toggle in about:config or hotkey via extension. It will be more modern (I think) and have a link between mainwindow and sidebar. (It seem like the sidebar situated under the mainwindow, very cool isnt it?)
The third idea is move the url bar to the bottom and add an toggle for it (because some people still like the top url bar). 
  
Otherwise, I haven't checked the alpha version yet because I only using firefox 129, and not even thinking of update in no time.

**Comment by quocjq** [comment]
Instead of using hotkey from extension, I think we hover mouse to the specific area to open sidebar and tool bar. And can make this like a mode.
![video](https://github.com/user-attachments/assets/1e72ce85-7683-4a4c-8c4b-998a2efbfa3c)
And you can add shadow to the border of mainwindow to pretend the mainwindow to on the above layer:
![image](https://github.com/user-attachments/assets/4ea12da6-bc84-4eb9-91a7-323a937d22f0)
In the video above you can see that the content of the web getting weird when open sidebar, it can be the hardest part to create the mode i mentioned
