### ISSUE TITLE
Drag and drop text

### ISSUE THREAD

**Issue by anoshione** [Naezr/ShyFox#18]
On previous version, you could drag and drop selected text to sidebery tab bar to search. but on v3 drag and drop isn't working anymore, is there a way to bring this back please?

**Comment by Naezr** [comment]
I don't think it's a problem on my part. Checked it right now, it's working for me. Try resetting Sidebery settings or clearing your browser profile entirely

**Comment by Naezr** [comment]
Doesn't work when the sidebar is hidden, is that what you mean? I'll see if I can fix it.

**Comment by Naezr** [comment]
The fix is already uploaded. I didn't even know that text could be drag-n-dropped into Sidebery

**Comment by anoshione** [comment]
> The fix is already uploaded. I didn't even know that text could be drag-n-dropped into Sidebery

Thanks a lot, yes I meant when sidebar is hidden. I used some hidden sidebar themes but none of them could drag and drop except yours, mind telling me how it works so I can figure it myself out in future please?

**Comment by Naezr** [comment]
For drag-n-drop to work, a piece of the sidebar workspace must remain on the screen. By workspace, I mean the area where the content of the extension opened in the sidebar is located. 

Perhaps other themes with a hidden sidebar change the width of the sidebar, but for me it goes off the screen with a static width. Perhaps such a small width of the whole sidebar makes the width of the workspace equal to 0px.

In my case, I just reduced the padding a bit, so that in the hidden state part of the workspace remains within the screen.

**Comment by anoshione** [comment]
I cant probably recreate what you mentioned on my own as I have minimal idea about how it works, but thank for explaining. 

Also I have been using this theme for a long time and absolutely love it. Really great work.
