### ISSUE TITLE
Hide sidebar top menu?

### ISSUE THREAD

**Issue by ingepettersen** [Naezr/ShyFox#182]
Just installed ShyFox today, and I'm loving it. But ss this supposed to show in the sidebar? I don't see it in any of your screenshots... How can I hide this menu?
![image](https://github.com/user-attachments/assets/2b809db7-3ac3-476c-8eff-4f95d78d9ec7)

**Comment by Naezr** [comment]
> But ss this supposed to show in the sidebar?

No. Perhaps you have Sidebery assigned some other ID and that's why the theme can't determine that it is Sidebery. 

- Try reinstalling Sidebery.

Make sure you installed right Sidebery, not some fork or other thing

![image](https://github.com/user-attachments/assets/45c0c9f6-5fcb-4a2f-8b8f-98903135bb54)

- Try installing ShyFox on a clean Firefox profile.

https://support.mozilla.org/kb/profile-manager-create-remove-switch-firefox-profiles

If still not, so

- Search for `#sidebar-box` via [Browser Toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) and make screenshot like this:

![image](https://github.com/user-attachments/assets/023dfcc0-b133-4ccc-8727-ade74ec6b826)

If the bunch of numbers and letters in the `sidebarcommand` attribute you have doesn't match what I have, then that's a problem, and I'll have to change my approach to Sidebery detection. If the IDs match, however, that's even weirder.

**Comment by ingepettersen** [comment]
Thanks! I had the Zen version of Sideberry installed, and didn't remember it 😐️ All good now.

**Comment by ingepettersen** [comment]
Fixed by installing correct Sideberry extension.
