### ISSUE TITLE
Searchbar sometimes is off screen

### ISSUE THREAD

**Issue by SirEthanator** [Naezr/ShyFox#2]
![image](https://github.com/Naezr/ShyFox/assets/130725768/27a8d2a9-e5d1-488c-9422-32ad9947e87c)

The searchbar is not visible all the time and I cannot figure out why. When I drag it up while customizing the toolbar it shows but goes back off screen when I let go of the mouse.

Edit: If density is changed in the "customize toolbar" page it shows up like normal.

**Comment by Naezr** [comment]
I ran into this a lot myself during development, and never seem to be able to beat it. It can be fixed by removing this selector, but after that the urlbar will not lock when the focus is on the address bar

![изображение](https://github.com/Naezr/ShyFox/assets/95460152/50796507-ab0e-4e7a-9d50-90295e286eca)

**Comment by Naezr** [comment]
I also see that you don't have fx-autoconfig installed. The script that moves the menu button, extensions button and overflow button to the side toolbar doesn't work for you

**Comment by SirEthanator** [comment]
Thanks, i do have fx-autoconfig installed however I will double check that I've followed the instructions correctly.

**Comment by Naezr** [comment]
Just want to point out that with fx-autoconfig installed, a new line in the menu appears
![изображение](https://github.com/Naezr/ShyFox/assets/95460152/eabe5dfa-12fd-452e-a00c-0a5b4a1a423c)
I've also updated the theme itself a bit and expanded the description, so check it out
