### ISSUE TITLE
wierd bug on websites that uses blur

### ISSUE THREAD

**Issue by luxluth** [Naezr/ShyFox#38]
![image](https://github.com/Naezr/ShyFox/assets/74856540/2d4cb8a9-9bb3-4074-9180-e81352982298)

The rounding on the corners is not applied on website that uses blur

**Comment by Naezr** [comment]
I've also noticed that, but didn't associate it with blur. Thanks for the lead! As I get time to dig deeper into it, I'll try to fix it

**Comment by luxluth** [comment]
What was the problem ?

**Comment by Naezr** [comment]
The problem hasn't gone anywhere. I just looked at how this problem was solved in [ArcWTF](https://github.com/KiKaraage/ArcWTF). It uses a psesudo element there that simulates rounded corners by overlaying them on top. The standard border-radius applied to content still breaks when there is blur on the site

**Comment by Naezr** [comment]
I just looked up the solution from [ArcWTF](https://github.com/KiKaraage/ArcWTF). It uses a psesudo element to simulate rounded corners. Instead of applying `border-radius` to the content, the rounded corners are made by a separate object overlaid on top. `border-radius` is still broken by blur.

**Comment by luxluth** [comment]
Okay I see, thanks

**Comment by Naezr** [comment]
Fix uploaded
