### ISSUE TITLE
Adress bar not center

### ISSUE THREAD

**Issue by Mojas84** [Naezr/ShyFox#54]
Hi Maybe I set something wrong, but the address bar looks weird to me.... And can't you get rid of those windows controls on the right and put the controls as seen in your picture....
![firefox_Roy3U06pAV](https://github.com/Naezr/ShyFox/assets/108186899/78507e71-d6d2-4118-a120-6fa9bee70c8d)

**Comment by Naezr** [comment]
The navbar did move up somewhere, I'll check it out on Windows. 

The window control buttons like I have in the pictures are available on Linux. They are buttons in the style of Adwaita, the standard GNOME desktop theme. There you can customize the position of the buttons both left and right, and enable or disable the minimize and maximize buttons.  This is system functionality, I just adapted the theme to it.

On Windows, this design would be a knockout. Control buttons on the left would confuse people. I use the standard button style on both Windows and Linux, as it's kind of a part of the system, supposedly out of the control of the application.

**Comment by Naezr** [comment]
I was able to reproduce this error. This requires the window to focus on the urlbar immediately when created. This happens if you don't save the previous session and the window starts from a new tab. I can probably fix it. 

Such errors have haunted this topic since its inception. Urlbar behaves unpredictably if the focus on it happens before the window is fully loaded
