### ISSUE TITLE
gif wallpaper

### ISSUE THREAD

**Issue by Felos9001** [Naezr/ShyFox#69]
Hello,

Is there a functionality for a gif wallpaper? I tried going into the  `shy-new-tab.css` to be able to modify this. (shown here) 

![image](https://github.com/Naezr/ShyFox/assets/90056233/452217f7-cd10-4d8d-88b0-0c5cbbabcc88)

but I havent been able to. the file below is what I am trying to use. it is a .mp4 file. 

https://github.com/Naezr/ShyFox/assets/90056233/543b4d42-5f1f-4ab2-91f8-8cdad6096601

**Comment by Naezr** [comment]
You cannot specify a path relative to the OS file system. You can only specify the path relative to the css file itself and only within the `chrome` folder

**Comment by Naezr** [comment]
You can try putting your `my-cool-animated-wallpaper.gif` file in the `chrome` folder. After that you should write the path `../../my-cool-animated-wallpaper.gif`.

Two dots means going higher up the hierarchy. Since `shy-new-tab` is in a subfolder within a subfolder, you have to go up. However, you cannot go beyond the `chrome` folder. Paths relative to the root are not supported.

**Comment by Naezr** [comment]
You can also try not changing the css at all, and just rename your video, gif or whatever to `wallpaper.png` and replace the existing file with it.
