### ISSUE TITLE
Clarify licencing 

### ISSUE THREAD

**Issue by awwsomepotato** [Naezr/ShyFox#88]
I would really appreciate it if you could add a license to this repo as currently using even a little of the code is legally dubious:
> [Without] a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
>
The [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/) or [MIT](https://opensource.org/license/MIT) licenses are both good options.

**Comment by Naezr** [comment]
Didn't even think about it, to be honest. Conditionally, if I add a license right now, will it apply to the whole repository (all commits before adding the license) or will only what was released with it be covered by the license?

Right now I have unreleased changes in the nightly branch, so it would be silly to add the license to main. Would it be right that I add the license to nightly and then later merge that branch into main?

I think Unlicense would be a good choice, I don't want to limit anyone. But I don't understand all these legal concepts at all, I'd be glad to hear your suggestions.

**Comment by Naezr** [comment]
I looked up the licenses of popular css themes for Firefox. Most of them use MPL 2.0. Since this license works for them, it works for me. ShyFox is a theme for Firefox - Mozilla software. It will be right to use their license. 

I still don't know much about licenses, but I assume MPL 2.0 will work for anyone who wants to use my code. I want to create and not be distracted by legal issues.
