### ISSUE TITLE
[Help]: Few Questions

### ISSUE THREAD

**Issue by niksingh710** [Naezr/ShyFox#9]
Firstly, loved this concept and theme... 

1. How to remove the padding around the webpage?
	
![image](https://github.com/Naezr/ShyFox/assets/60490474/2bdacd8c-17c1-4ed0-9f3a-d0fcb5fa3ea3)

2. Make `Ctrl+Alt+W` one (The floating view of sidebar) as default when the browser launches? (the one in screenshot)
![image](https://github.com/Naezr/ShyFox/assets/60490474/2800812a-c8be-4b5d-ada0-6ba71a4c2e45)

3. How to keep the url input suggestion at the bottom only? 
![image](https://github.com/Naezr/ShyFox/assets/60490474/41cbc260-dadc-419b-b525-be5d9e272960)

4. pinned extensions on the right floating window instead of the one where the url bar is?

**Comment by niksingh710** [comment]
5. how to get url bar text input center aligned?

**Comment by Naezr** [comment]
1. If you comment out [this](https://github.com/Naezr/ShyFox/blob/main/userChrome.css#L115-L125) piece of code, the padding around the page will disappear. But I'm not responsible for anything looking wrong without it.
2. I have Userchrome Toggle saves states on restart, I don't understand what exactly you need. But because the sidebar is initially visible and hidden only through UC Toggle, some super rare popups break, like Google account login windows. So maybe I'll change that somehow.
3. Do I understand correctly that you want to completely remove the urlbar popup in the center of the screen and make the input field stay at the bottom and suggestions appear above it? This is possible, but obviously requires some minor modifications.
4. Open firefox customization menu and move all icons to where you want them.
5. Do you want the bottom bar to not move relative to the sidebar? That's also possible.

Right now I don't have time to deal with these issues in depth, try to figure it out for yourself. But I will help you when I have time

**Comment by niksingh710** [comment]
1. Worked
2. I had it misconfigured, now referenced it from image and it worked.
3. Yes
4. I don't get my extensions listed there.
5. No not that, I want the text to be aligned in the center of the url bar.

#### New
1. How do I fix this height issue?
![image](https://github.com/Naezr/ShyFox/assets/60490474/28340949-573e-43c7-9398-f964cf46e33e)

Thanks for this much help buddy. It works perfectly fine.

**Comment by niksingh710** [comment]
4. is resolved to.
Now just that New-1.

**Comment by niksingh710** [comment]
![image](https://github.com/Naezr/ShyFox/assets/60490474/a94de6b7-133c-47a4-b073-533ea8969902)
Maybe this screenshot clarifies it.
The string in the menu bar is not having padding.
It feels like they are cutted.

**Comment by Naezr** [comment]
Add this somewhere:
```
#main-menubar *{
  padding-top: 0px !important;
}
```
And add `!important` [there](https://github.com/Naezr/ShyFox/blob/e2cd7d423bd57c182e5060bca8610591dd228c8c/userChrome.css#L402) to fix transparent background

**Comment by niksingh710** [comment]
Thanks mate for helping on every step.
