### ISSUE TITLE
When clicking on address bar, existing text is not highlighted automatically

### ISSUE THREAD

**Issue by nirurin** [Naezr/ShyFox#94]
On web browsers generally (and on Firefox my default) when you click on the address bar any existing text in the bar is highlighted automatically. So you can just start typing and it will overwrite what was there before. 

However for whatever reason, in shyfox when you click on the address bar it just puts the cursor to the start of the address line, without highlighting the text. So if you start typing, you're just adding to the beginning of the existing URL (which obviously results in a non-working link). 

Edit: actually it seems it's not always the start of the field. The cursor ends up relative to where on the address bar you clicked. But that doesn't really help as you'd mostly want to overwrite the entire URL by default anyway, and you can't do that without additional drags/clicks/keypresses.

**Comment by Naezr** [comment]
![image](https://github.com/user-attachments/assets/a16bb124-bc0f-4626-b883-bacbc57ec6f7)

For some reason the text is not highlighted if the address bar position is changed. Customize search suggestions so that urlbar does not expand the moment you decide to highlight an address on an already opened page. Alternatively, turn off the floating urlbar via about:config

[Запись экрана от 2024-07-18 10-22-59.webm](https://github.com/user-attachments/assets/08f68812-eff5-4a35-aceb-5fb91063ea0d)

**Comment by nirurin** [comment]
Hmm, weirdly when I go into about.config and look for shyfox entries, there are none listed...

**Comment by Naezr** [comment]
That's the way it should be, copy and paste them yourself

**Comment by nirurin** [comment]
ahh, sorry I'm still pretty new to firefox. That works anyway. Thankyou so much :)
